# Generated by Django 5.0.4 on 2024-04-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_productos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(upload_to='coppel-back/resources/images'),
        ),
    ]
